[bindings.acceptSuggestion]
key = "right"
# shift and ctrl are optional and default to false
shift = true
ctrl = false

[bindings.nextSuggestion]
key = "down"

[bindings.previousSuggestion]
key = "up"

[bindings.dismissSuggestions]
key = "escape"
